[colors.bright]
black = "0x5b6078"
blue = "0x8aadf4"
cyan = "0x8bd5ca"
green = "0xa6da95"
magenta = "0xf5bde6"
red = "0xed8796"
white = "0xa5adcb"
yellow = "0xeed49f"

[colors.normal]
black = "0x494d64"
blue = "0x8aadf4"
cyan = "0x8bd5ca"
green = "0xa6da95"
magenta = "0xf5bde6"
red = "0xed8796"
white = "0xb8c0e0"
yellow = "0xeed49f"

[colors.primary]
background = "#24273a"
foreground = "#cad3f5"

[font]
size = 14.0

[window]
opacity = 0.9

[window.padding]
x = 15
y = 15
