[[language]]
  name = "lua"
  injection-regex = "lua"
  scope = "source.lua"
  file-types = ["lua"]
  shebangs = ["lua"]
  roots = [".luarc.json", ".luacheckrc", ".stylua.toml", "selene.toml", ".git"]
  comment-token = "--"
  indent = { tab-width = 2, unit = "  " }

[[grammar]]
  name = "lua"
  source = { git = "https://github.com/MunifTanjim/tree-sitter-lua", rev = "887dfd4e83c469300c279314ff1619b1d0b85b91" }

[[language]]
  name = "html"
  injection-regex = "html"
  scope = "text.html.basic"
  file-types = ["html"]
  roots = [".git"]
comment-token = "<!--"
  indent = { tab-width = 2, unit = "  " }

[[grammar]]
  name = "html"
  source = { git = "https://github.com/tree-sitter/tree-sitter-html", rev = "a9e7f3b8e5d0a4c6f8d3a3b2e1c0d4e5f6a7b8c9" }

[[language]]
  name = "css"
  injection-regex = "css"
  scope = "text.html.basic"
  file-types = ["css"]
  roots = [".git"]
  comment-token = "/*"
  indent = { tab-width = 2, unit = "  " }

[[grammar]]
  name = "css"
  source = { git = "https://github.com/tree-sitter/tree-sitter-css", rev = "769203d0f9abe1a9a691ac2b9fe4bb4397a73c51" }

[[language]]
  name = "scss"
  injection-regex = "scss"
  scope = "source.scss"
  file-types = ["scss"]
  roots = [".git"]
  comment-token = "//"
  indent = { tab-width = 2, unit = "  " }

[[grammar]]
  name = "scss"
  source = { git = "https://github.com/tree-sitter/tree-sitter-scss", rev = "c478c6868648eff49eb04a4df90d703dc45b312a" }

[[language]]
  name = "toml"
  injection-regex = "toml"
  scope = "source.toml"
  file-types = ["toml"]
  roots = [".git"]
  comment-token = "#"

[[grammar]]
name = "toml"
source = { git = "https://github.com/ikatyang/tree-sitter-toml", rev = "7cff70bbcbbc62001b465603ca1ea88edd668704" }

[[language]]
  name = "lua"
  injection-regex = "lua"
  scope = "source.lua"
  file-types = ["lua"]
  roots = [".luarc.json", ".luacheckrc", ".stylua.toml", "selene.toml", ".git"]
  comment-token = "--"
  indent = { tab-width = 2, unit = "  " }

[[grammar]]
  name = "lua"
  source = { git = "https://github.com/MunifTanjim/tree-sitter-lua", rev = "887dfd4e83c469300c279314ff1619b1d0b85b91" }

[[language]]
  name = "json"
  injection-regex = "json"
  scope = "source.json"
  file-types = ["json"]

[[language]]
name="bash"
injection-regex="bash|sh|zsh|ksh|dash|ash|csh|tcsh|fish|busybox|mksh|pdksh|posh|yash|dash-static|bash-static|zsh-static|ksh-static|fish-static|busybox-static|mksh-static|pdksh-static|posh-static|yash-static"
scope="source.shell.bash"
file-types=["sh","bash",".bashrc",".bash_profile",".bash_login",".profile",".bash_logout",".bash_aliases",".bash_history",".zshrc",".zprofile",".zlogin",".zlogout",".zaliases",".zhistory",".kshrc",".ksh_profile",".ksh_login",".ksh_logout",".ksh_aliases",".ksh_history",".cshrc",".tcshrc",".csh_profile",".tcsh_profile",".csh_login",".tcsh_login",".csh_logout",".tcsh_logout"]
roots=["/etc/profile.d/"]
comment-token="#"

[[grammar]]
name="bash"
source={git="https://github.com/tree-sitter/tree-sitter-bash",rev="275effdfc0edce774acf7d481f9ea195c6c403cd"}
